package com.ekta.myapp.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;

@Entity //Database Entity for person
@Table(name="person_tbl") //Table name for this entity
@Inheritance(strategy=InheritanceType.JOINED) //This is a superclass
public class Person {
	
	@Id //This is primary key
	@GeneratedValue //Auto generated by ODB
	@Column(name="personID",unique=true,nullable=false) //Table attribute (Column), id should be unique
	private long personID;
	
	@Column(name="firstName") //First name attribute for person table
	private String firstName;
	
	@Column(name="lastName") //Last name attribute for person table
	private String lastName;
	
	@Column(name="emailID") //Email attribute for person table
	private String emailID;
	
	@Column(name="city") //City attribute for person table
	private String city;
	
	@Column(name="username") //Username attribute for person table
	private String username;
	
	@Column(name="password") //Password attribute for person table
	private String password;
	
	@Column(name="roleType") //Roletype attribute for person table; can be user or restAdmin
	private String roleType;
	

	
	
	public Person(){
		
	}
	
	/* ******** Getter and Setter functions START ******** */
	public long getPersonID() {
		return personID;
	}

	public void setPersonID(long personID) {
		this.personID = personID;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmailID() {
		return emailID;
	}

	public void setEmailID(String emailID) {
		this.emailID = emailID;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRoleType() {
		return roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	/* ******** Getter and Setter functions END ******** */
	
	

}
